steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$_PROJECT_ID/$_IMAGE_NAME
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$_PROJECT_ID/$_IMAGE_NAME
